window.hotelRenderPage = ({page, path, t, labels, rooms, roomCard, roomIntro, hero, heading, banner, link, url, amenityNames, stories, storyCard, faqs, requestLink, socials, stayFields, routes}) => {
 if(page==='rooms')return hero(t('marketing.m_e698b193ae57'),t('marketing.m_69dbbcff35a1'),'room-2-0.jpg')+`<section class="page-body">${heading(t('marketing.m_6b68f47c6c4e'),t('marketing.m_5f5b6a55d00a'),t('marketing.m_d2a5282535f6'))}<div class="filter-row" aria-label="${t('marketing.m_7d9092b09461')}">${['all','deluxe','superior','standard'].map(k=>`<button data-filter="${k}" aria-pressed="${k==='all'}">${labels[k]}</button>`).join('')}</div><div class="room-grid">${rooms.map((r,i)=>roomCard(r,i)).join('')}</div><div class="home-note" style="padding-inline:0"><div><span class="eyebrow">${t('marketing.m_8f8bb5caae56')}</span><h2>${labels.domes}</h2><p>${t('marketing.m_533127151c29')}</p></div><a class="text-link" href="${url('/rooms/copper-glass-domes/')}">${labels.more}</a></div></section>`;
 if(page==='room'){
 const slug=path.split('/').pop();const r=rooms.find(r=>r.slug===slug);
 if(slug==='copper-glass-domes')return hero(t('marketing.m_c5e7a2cdb10a'),t('marketing.m_0173b92f891c'),'hero.jpg','rooms')+`<section class="page-body"><div class="split-story"><img src="assets/03-1.jpg" alt="${labels.domes}"><div><span class="eyebrow">${t('marketing.m_5e8eddc78247')}</span><h2>${t('marketing.m_6d6b9c268b17')}</h2><p>${t('marketing.m_c429d04e291e')}</p><a class="button" href="${url('/')}#architecture">${t('marketing.m_2ab113e990e6')}</a></div></div>${banner()}<div class="detail-gallery">${['hero.jpg','05-1.jpg'].map(img=>`<button data-lightbox="${img}" data-caption="${labels.domes}"><img src="assets/${img}" alt="${labels.domes}"></button>`).join('')}</div><div class="home-note"><a class="text-link" href="${url('/contact-us/')}">${t('marketing.m_6024ad8f75df')}</a></div></section>`;
 if(!r)return hero(labels.rooms,'')+`<section class="page-body error-panel"><h2>${t('marketing.m_0d12b4b59c09')}</h2>${link('rooms')}</section>`;
 return hero(r.name,roomIntro(r.category),`room-${r.id}-0.jpg`,'rooms')+`<section class="page-body"><div class="detail-layout"><div><span class="eyebrow">${labels[r.category]} / B&W SAHARA SKY</span><h2>${t('marketing.m_580a7b101c0d')}</h2><p>${roomIntro(r.category)}</p><div class="spec-list"><span>${r.size} m²</span><span>${r.beds}</span><span>${t('marketing.m_0728ed491b94')}</span></div><h3 style="font-size:31px">${t('marketing.m_42e7bb486348')}</h3><div class="amenities">${amenityNames.map(a=>`<span>${a}</span>`).join('')}</div><p class="room-warning">${t('marketing.m_1b90569ecb76')}</p></div><aside class="booking-aside"><span class="eyebrow">${t('marketing.m_02bfb00f8711')}</span><h3>${t('marketing.m_a9ce965c687c')}</h3><p>${t('marketing.m_f281b7b82554')}</p><button class="button" data-book data-room-id="${r.id}">${labels.availability}</button><a class="text-link" href="${url('/contact-us/')}">${t('marketing.m_9e7a449c032e')}</a></aside></div><div class="detail-gallery">${[0,1,2].map((n)=>`<button data-lightbox="room-${r.id}-${n}.jpg" data-caption="${r.name} · ${t('marketing.m_a738f7df0b17')}"><figure><img src="assets/room-${r.id}-${n}.jpg" alt="${r.name} — ${n+1}" loading="lazy"><figcaption>${String(n+1).padStart(2,'0')} / ${r.name} <span aria-hidden="true"></span></figcaption></figure></button>`).join('')}</div><div style="margin-top:70px">${heading(t('marketing.m_b21309002ceb'),t('marketing.m_e139af29df88'))}<div class="room-grid">${rooms.filter(o=>o.id!==r.id).slice(0,2).map(roomCard).join('')}</div></div></section>`;
 }
 if(page==='about')return hero(t('marketing.m_437c10c30610'),t('marketing.m_3c925e2ad2ba'),'05-1.jpg')+`<section class="page-body"><div class="split-story"><img src="assets/exterior.jpg" alt="B&W Sahara Sky Hotel" loading="lazy"><div><span class="eyebrow">${t('marketing.m_59f844d75ab0')}</span><h2>${t('marketing.m_96b7db7b46c7')}</h2><p>${t('marketing.m_ec629a0d3749')}</p><p>${t('marketing.m_b496134486c4')}</p><a class="text-link" href="${url('/rooms/')}">${labels.viewRooms}</a></div></div><div class="values-row">${[[t('marketing.m_d4ebbb3f9c42'),t('marketing.m_deab7e1bffc0')],[t('marketing.m_6b6ed42e4d73'),t('marketing.m_b9f675548255')],[t('marketing.m_2cb7741bfe0a'),t('marketing.m_f52131d4108b')]].map(([h,p],i)=>`<div><span class="eyebrow">0${i+1}</span><h3>${h}</h3><p>${p}</p></div>`).join('')}</div><div class="home-note" style="padding-inline:0"><div><h2>${t('marketing.m_215f5bdfafed')}</h2></div><a class="text-link" href="${url('/contact-us/')}">${labels.contact}</a></div></section>`;
 if(page==='services')return hero(t('marketing.m_5f5839917acd'),t('marketing.m_18b5e1b3033b'),'desert.jpg')+`<section class="page-body">${heading(t('marketing.m_c6580534826e'),t('marketing.m_47bbb3805af7'))}<div class="service-grid">${[
 [t('marketing.m_d401d395e809'),t('marketing.m_1072f89a5641')],
 [t('marketing.m_babe1044b4ad'),t('marketing.m_c3288af3e79c')],
 [t('marketing.m_a0352d92eab9'),t('marketing.m_167d394944bc')],
 [t('marketing.m_e60e74ff9875'),t('marketing.m_b38f0754304b')],
 [t('marketing.m_1f495cde7a2b'),t('marketing.m_bc4a0c90c69c')],
 [t('marketing.m_313b2dd193b2'),t('marketing.m_ba4958589171')]
 ].map(([h,p],i)=>`<article class="service"><span aria-hidden="true">${['◈','✧','≈','⌁','❋','☼'][i]}</span><h3>${h}</h3><p>${p}</p></article>`).join('')}</div><div class="home-note" style="padding-inline:0"><div><h2>${t('marketing.m_e5dd9afa8ec5')}</h2><p>${t('marketing.m_cd43e0d3fce7')}</p></div><a class="text-link" href="${url('/experiences/')}">${labels.experiences}</a></div></section>`;
 if(page==='experiences')return hero(t('marketing.m_8937c08888b5'),t('marketing.m_9af53fa9a0b5'),'04-1.jpg')+`<section class="page-body">${[
 ['exterior.jpg',t('marketing.m_fbdda19a48ee'),t('marketing.m_06e15c14fb97'),t('marketing.m_195c134a6d55')],
 ['04-1.jpg',t('marketing.m_9c751c6fd9fb'),t('marketing.m_be153a6e363a'),t('marketing.m_4f99ff6aa81f')],
 ['desert.jpg',t('marketing.m_73cd65408659'),t('marketing.m_6f8b9ef25a2a'),t('marketing.m_2938ffbfbe3e')]
 ].map(([img,over,h,p])=>`<article class="experience-wide"><img src="assets/${img}" alt="${h}" loading="lazy"><div><span class="eyebrow">${over}</span><h2>${h}</h2><p>${p}</p>${requestLink}<p class="preview-note">${t('marketing.m_b608afa6a837')}</p></div></article>`).join('')}</section>`;
 if(page==='gallery'){
 const pictures=[['hero.jpg','domes',labels.domes],['room-2-0.jpg','deluxe',rooms[0].name],['room-6-0.jpg','superior',rooms[3].name],['desert.jpg','hotel',t('marketing.m_196394a7e9ce')],['room-5-0.jpg','standard',rooms[4].name],['04-1.jpg','domes',t('marketing.m_2b73df1782ad')],['03-1.jpg','domes',labels.domes],['room-1-1.jpg','deluxe',rooms[1].name],['exterior.jpg','hotel',t('marketing.m_c89c0fc4d737')],['05-1.jpg','domes',t('marketing.m_9f0c803031a4')],['desert-arrival.png','concept',labels.visualisation],['desert-farewell.png','concept',labels.visualisation]];
 return hero(t('marketing.m_ee5b5ab1eaf7'),t('marketing.m_16e881ca4489'),'03-1.jpg')+`<section class="page-body"><div class="filter-row">${['all','hotel','deluxe','superior','standard','domes','concept'].map(k=>`<button data-filter="${k}" aria-pressed="${k==='all'}">${labels[k]||(k==='hotel'?t('marketing.m_a4f99c1f513d'):labels.visualisation)}</button>`).join('')}</div><div class="gallery-grid">${pictures.map(([img,cat,caption])=>`<button class="gallery-item" data-category="${cat}" data-lightbox="${img}" data-caption="${caption}" aria-label="${labels.photo}: ${caption}"><figure><img src="assets/${img}" alt="${caption}" loading="lazy"><figcaption>${caption}</figcaption></figure></button>`).join('')}</div></section>`;
 }
 if(page==='blog')return hero(t('marketing.m_27097ca1c99f'),t('marketing.m_ca46181e84cd'),'exterior.jpg')+`<section class="page-body"><span class="eyebrow">${t('marketing.m_a879720a6603')}</span><div class="article-grid" style="margin-top:30px">${stories.map(storyCard).join('')}</div><p class="preview-note">${t('marketing.m_de980fa257e5')}</p></section>`;
 if(page==='article'){
 const s=stories.find(s=>s.slug===path.split('/').pop());if(!s)return hero(labels.blog,'');
 const body = s===stories[0] ? [
 [t('marketing.m_7952f618b927'),t('marketing.m_fcd55c91ad9b')],
 [t('marketing.m_4fa569d4b1c3'),t('marketing.m_647d7c202b4d')]
 ] : s===stories[1] ? [
 [t('marketing.m_fd60245c05e5'),t('marketing.m_458b17c3af21')],
 [t('marketing.m_90fd0fd31f7c'),t('marketing.m_18216a047275')]
 ] : [
 [t('marketing.m_55ea2e88241a'),t('marketing.m_a8ff16544486')],
 [t('marketing.m_89583c56b2b4'),t('marketing.m_0c5efb158b54')]
 ];
 return hero(s.title,s.intro,s.image,'blog')+`<section class="page-body"><div class="reading-layout"><article class="reading-copy"><div class="article-meta">${s.topic} · ${t('marketing.m_a2d9d07dbec0')}</div><p class="lead">${s.intro}</p>${body.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('')}<img src="assets/${s.image}" alt="${s.title}" loading="lazy"><p class="preview-note">${t('marketing.m_98c2b7d5026f')}</p><a class="text-link" href="${url('/contact-us/')}">${labels.contact}</a></article><aside class="related-stories"><span class="eyebrow">${t('marketing.m_5de41b8f1382')}</span><h3>${t('marketing.m_9b58db23cb18')}</h3>${stories.filter(o=>o!==s).map(o=>`<a href="${url('/blog/'+o.slug+'/')}">${o.title}</a>`).join('')}<a href="${url('/rooms/')}">${labels.viewRooms}</a></aside></div></section>`;
 }
 if(page==='contact')return hero(t('marketing.m_62c4b73c6484'),t('marketing.m_0d93c09f56d2'),'exterior.jpg')+`<section class="page-body"><div class="contact-layout"><div class="contact-details"><span class="eyebrow">${t('marketing.m_5292b7b7ba67')}</span><h2>${t('marketing.m_a957405f95c0')}</h2><a href="tel:+201098255777" dir="ltr">+20 109 825 5777</a><a href="mailto:${window.__HOTEL_SEO__.entity.email}">${window.__HOTEL_SEO__.entity.email}</a><a href="https://wa.me/201098255777" target="_blank" rel="noopener">WhatsApp</a><p><a class="map-link" href="https://maps.app.goo.gl/EVzKGmchofL5DgaFA" target="_blank" rel="noopener" aria-label="${t('marketing.m_475c890946bf')}">${t('marketing.m_43363af16409')}</a></p>${socials}</div><form class="approval-form" id="contact-form"><div class="form-grid"><label>${labels.name}<input name="name" autocomplete="off" required maxlength="100"></label><label>${labels.email}<input name="email" type="email" autocomplete="off" required></label><label class="full">${t('marketing.m_d7565998aa19')}<select name="subject"><option>${t('marketing.m_028bd222c808')}</option><option>${t('marketing.m_313b2dd193b2')}</option><option>${t('marketing.m_8980cde0c43e')}</option><option>${t('marketing.m_658cb7a150a4')}</option></select></label><label class="full">${t('marketing.m_1ab4119f7c38')}<textarea name="message" required maxlength="3000"></textarea></label></div><button class="button" type="submit">${t('marketing.m_c16ce506a403')}</button><p class="form-status" role="status"></p><p class="preview-note">${t('marketing.m_981d2012fde3')}</p></form></div><div class="location-panel"><div><span class="eyebrow">${t('marketing.m_4a590a94391f')}</span><h3>${t('marketing.m_4fd5a24da1c8')}</h3><p>${t('marketing.m_45bee91a47e5')}</p><a class="text-link" href="https://wa.me/201098255777" target="_blank" rel="noopener">${t('marketing.m_f6ef1a65c794')}</a></div></div></section>`;
 if(page==='faq')return hero(t('marketing.m_a750e5c75fc6'),t('marketing.m_e76c01343cb5'),'desert.jpg')+`<section class="page-body"><div class="faq-layout"><aside><span class="eyebrow">${t('marketing.m_8cabc3a48e2f')}</span><h2>${t('marketing.m_1bd059bb6f27')}</h2><p>${t('marketing.m_12d94e6e4a7b')}</p><a class="text-link" href="${url('/contact-us/')}">${labels.contact}</a></aside><div>${faqs()}</div></div></section>`;
 if(page==='privacy'||page==='terms'){
 const privacy=page==='privacy';
 const sections=privacy?[
 [t('marketing.m_36f06ef6f8ca'),t('auth.m_565630ad0ef5')],
 [t('marketing.m_9e5ff90655ce'),t('marketing.m_179d27f9db15')],
 [t('marketing.m_4d03b0881456'),t('marketing.m_ce343440c203')]
 ]:[
 [t('marketing.m_6c50ccc22681'),t('marketing.m_dd00670f18c4')],
 [t('marketing.m_fd757489d426'),t('marketing.m_9f0bf1f9bcf9')],
 [t('marketing.m_af7e30c22229'),t('marketing.m_9255d8e17eba')],
 [t('marketing.m_ab27e4784f7a'),t('marketing.m_109131a19ffa')]
 ];
 return hero(labels[page],t('marketing.m_f00fb65350ff'),'exterior.jpg')+`<section class="page-body"><article class="policy-content">${banner()}${sections.map(([h,p])=>`<h2>${h}</h2><p>${p}</p>`).join('')}<a class="text-link" href="${url('/contact-us/')}">${labels.contact}</a></article></section>`;
 }
 if(['login','register','forgot'].includes(page)){
 const register=page==='register',forgot=page==='forgot';
 return `<section class="auth-layout"><div class="auth-image"><h1>${t('marketing.m_69f6bb2e0d73')}</h1></div><div class="auth-panel"><span class="eyebrow">B&W SAHARA SKY</span><h2>${labels[page]}</h2><form class="approval-form" id="auth-form">${register?`<label>${labels.name}<input name="name" required autocomplete="off"></label>`:''}<label>${labels.email}<input type="email" name="email" required autocomplete="off" placeholder="demo@example.com"></label>${!forgot?`<label>${labels.password}<input type="password" name="password" minlength="6" required autocomplete="off" placeholder="${t('marketing.m_a9bc5c6eeb16')}"></label>`:''}<button class="button" type="submit">${t('marketing.m_90400b9dc364')}</button><p class="form-status" role="status"></p><p class="preview-note">${t('auth.m_7dd1161da37a')}</p></form>${register||forgot?link('login'):link('register')}${!register&&!forgot?link('forgot'):''}</div></section>`;
 }
 if(page==='booking')return hero(t('marketing.m_676f4f5d4369'),t('marketing.m_d10c92851689'),'hero.jpg')+`<section class="page-body"><div class="booking-steps"><span>01 / ${t('marketing.m_d5993552b940')}</span><span>02 / ${t('marketing.m_597d17c0c79d')}</span><span>03 / ${t('marketing.m_693783099081')}</span></div><div class="detail-layout"><div><form id="booking-search" class="approval-form">${stayFields()}<button class="button" type="submit">${t('marketing.m_9e176b5aba20')}</button><p class="form-status" role="status"></p></form></div><aside class="booking-aside"><h3>${t('marketing.m_5f7b8071d77d')}</h3><p>${labels.demoNote}</p><p>${t('marketing.m_cc4dfb6758a5')}</p></aside></div><section class="booking-results" hidden><div class="review-summary" id="search-summary"></div>${heading(t('marketing.m_49a496854823'),t('marketing.m_6b9269de0f73'))}<p class="preview-note">${t('marketing.m_453caad443d6')}</p><div class="room-grid">${rooms.map((r,i)=>roomCard(r,i,true)).join('')}</div></section></section>`;
 if(page==='review')return hero(labels.review,t('marketing.m_79aa8a1c53d2'),'05-1.jpg')+`<section class="page-body"><div class="booking-steps"><span>01 / ${t('marketing.m_d5993552b940')}</span><span>02 / ${t('marketing.m_597d17c0c79d')}</span><span>03 / ${t('marketing.m_693783099081')}</span></div><div id="review-state"></div></section>`;
 if(page==='confirmation')return hero(labels.confirmation,t('marketing.m_f6ad064188f2'),'04-1.jpg')+`<section class="page-body"><div class="complete-state"><span aria-hidden="true">✧</span><h2>${t('marketing.m_15263c472314')}</h2><p>${t('marketing.m_35a9893d30a3')}</p><div id="confirmation-summary"></div><a class="button" href="${url('/contact-us/')}">${t('marketing.m_1a0b7ac2699b')}</a><br><a class="text-link" href="${url('/booking/')}">${t('marketing.m_f732699f7aa1')}</a></div></section>`;
 if(page==='approval')return hero(t('marketing.m_2830b9261797'),t('marketing.m_8c48621e37f4'),'desert-arrival.png')+`<section class="page-body">${heading(t('marketing.m_ed033252292e'),t('marketing.m_cc76cae7df64'),t('marketing.m_47406993b738'))}<div class="service-grid">${['home','rooms','about','services','experiences','gallery','blog','contact','faq','privacy','terms','login','register','forgot','booking'].map((k,i)=>`<article class="service"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${labels[k]}</h3><a class="text-link" href="${url(routes[k])}">${t('marketing.m_c54b89bdac63')}</a></article>`).join('')}</div><div style="margin-top:50px">${banner()}<p class="preview-note">${t('marketing.m_830ea19f0b58')}</p></div></section>`;
 return hero('404',t('marketing.m_832e8f5f044f'))+`<section class="page-body error-panel"><a class="button" href="${url('/')}">${labels.home}</a></section>`;
 };
