import assert from 'node:assert/strict';import {chromium} from 'playwright';import {readFile,writeFile,mkdir} from 'node:fs/promises';
const admin=JSON.parse(await readFile('../BW-Sahara-Sky-Hotel/tmp/local-integration-20261007/private-admin-access.json','utf8'));
const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block',hasTouch:true});const p=await context.newPage(),checks=[],errors=[];p.setDefaultTimeout(30000);p.setDefaultNavigationTimeout(60000);p.on('pageerror',e=>errors.push(e.message));await p.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await mkdir('test-results/admin-mobile',{recursive:true});
try{
await p.goto('http://127.0.0.1:8782/admin/login');await p.locator('[name=username]').fill(admin.username);await p.locator('[name=password]').fill(admin.password);await p.locator('button[type=submit]').click();await p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:30000});console.log('Authenticated local admin');
for(const width of (process.env.HOTEL_ADMIN_INTERACTIONS_ONLY ? [] : process.env.HOTEL_ADMIN_QUICK_CHECK ? [390] : [320,390,768,1440])){
 await p.setViewportSize({width,height:width===1440?900:844});
 for(const [name,path] of [['dashboard','/admin'],['media','/admin/media'],['rooms','/admin/hotel/rooms'],['bookings','/admin/hotel/bookings']]){await p.goto('http://127.0.0.1:8782'+path,{waitUntil:'domcontentloaded',timeout:60000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),`${name} ${width}: overflow`);checks.push(`${name} at ${width}px: no page overflow`);if(width===390||width===1440)await p.screenshot({path:`test-results/admin-mobile/after-${name}-${width}.png`,fullPage:true});}
}
if(!process.env.HOTEL_ADMIN_EDITOR_ONLY){await p.setViewportSize({width:390,height:844});await p.goto('http://127.0.0.1:8782/admin/media',{waitUntil:'domcontentloaded'});
console.log('Waiting for media folder controls');await p.waitForSelector('.bw-media-open');await p.screenshot({path:'test-results/admin-mobile/after-media-390.png'});const toggle=p.locator('#sidebar-menu-main > div > .navbar-toggler');assert((await toggle.boundingBox()).height>=44);checks.push('Navigation toggle is at least 44px');await toggle.click();await p.waitForFunction(()=>document.body.classList.contains('bw-admin-menu-open'));assert(await p.locator('.page-wrapper').evaluate(e=>e.inert));assert.equal(await p.locator('#sidebar-menu').getAttribute('aria-modal'),'true');await p.screenshot({path:'test-results/admin-mobile/mobile-navigation.png'});await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.body.classList.contains('bw-admin-menu-open'));assert.equal(await p.locator('.page-wrapper').evaluate(e=>e.inert),false);checks.push('Mobile menu opens, isolates background and closes with Escape');
await toggle.click();await p.waitForFunction(()=>document.body.classList.contains('bw-admin-menu-open'));await p.locator('.bw-mobile-menu-heading button').click();await p.waitForFunction(()=>!document.body.classList.contains('bw-admin-menu-open'));checks.push('Mobile menu close button works');
await p.waitForSelector('.bw-media-open');const opener=p.locator('.bw-media-open').first();const folderName=await opener.evaluate(e=>e.closest('.js-media-list-title').querySelector('.title,.rv-media-file-name')?.textContent.trim());const box=await opener.boundingBox();assert(box.width>=44&&box.height>=44);await opener.click();await p.waitForFunction(name=>document.querySelector('.rv-media-breadcrumb .breadcrumb')?.textContent.includes(name),folderName);checks.push('Folder opens with one tap using native navigation');await p.screenshot({path:'test-results/admin-mobile/folder-open.png'});
await p.goto('http://127.0.0.1:8782/admin/media',{waitUntil:'domcontentloaded'});await p.locator('[href="#rv-media-aside"]').click();await p.waitForSelector('#rv-media-aside.show');await p.locator('#rv-media-aside [data-bs-dismiss="offcanvas"]').click();await p.waitForFunction(()=>!document.querySelector('#rv-media-aside').classList.contains('show'));checks.push('Media filters open and close normally');
}console.log('Checking room editor');const rows=await(await p.request.get('http://127.0.0.1:8782/api/hotel/rooms')).json();await p.goto('http://127.0.0.1:8782/admin/hotel/rooms/edit/'+rows.rooms[0].id,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForSelector('input[name=name]');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'room editor overflow');const name=p.locator('input[name=name]');assert.equal(await name.evaluate(e=>getComputedStyle(e).fontSize),'16px');checks.push('Room editor fits mobile with 16px inputs');await p.screenshot({path:'test-results/admin-mobile/room-editor.png',fullPage:true});
await p.evaluate(()=>document.body.setAttribute('dir','rtl'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'RTL overflow');checks.push('RTL layout has no horizontal page overflow');await p.screenshot({path:'test-results/admin-mobile/room-editor-rtl.png'});
assert.deepEqual(errors,[]);checks.push('No JavaScript page errors');await writeFile('test-results/admin-mobile/results.json',JSON.stringify({passed:true,checks,errors},null,2));console.log(JSON.stringify({passed:true,checks}));
}catch(e){await p.screenshot({path:'test-results/admin-mobile/failure.png',fullPage:true}).catch(()=>{});console.log(JSON.stringify({passed:false,checks,error:e.message,errors}));process.exitCode=1;}finally{await b.close();}
