(() => {
  'use strict';
  const nativeAdd = EventTarget.prototype.addEventListener;
  const nativeRemove = EventTarget.prototype.removeEventListener;
  const NativeIntersection = window.IntersectionObserver;
  const NativeMutation = window.MutationObserver;
  const views = new Map();
  const initial = { active: true, listeners: [], observers: [], page: document.body.dataset.page };
  let current = initial;
  window.__hotelViewScope = initial;
  const metrics = window.hotelPerformance = {
    sceneLoads: 0, modelBuilds: 0, renderersCreated: 0, clientNavigations: 0,
    largestContentfulPaint: null, cumulativeLayoutShift: 0,
  };
  function scoped(scope, callback, receiver, args) {
    const previous = window.__hotelViewScope;
    window.__hotelViewScope = scope;
    try { return callback.apply(receiver, args); }
    finally { window.__hotelViewScope = previous; }
  }
  // Route scripts keep their original closures and DOM. Inactive views cannot react to events.
  // The persistent 3D controller runs outside this scope and survives route changes.
  EventTarget.prototype.addEventListener = function (type, handler, options) {
    const scope = window.__hotelViewScope;
    if (!scope || !handler) return nativeAdd.call(this, type, handler, options);
    const wrapped = function (...args) {
      if (!scope.active) return;
      return scoped(scope, typeof handler === 'function' ? handler : handler.handleEvent, typeof handler === 'function' ? this : handler, args);
    };
    scope.listeners.push([this, type, handler, wrapped, options]);
    return nativeAdd.call(this, type, wrapped, options);
  };
  EventTarget.prototype.removeEventListener = function (type, handler, options) {
    for (const view of [initial, ...views.values()]) {
      const entry = view.listeners?.find(x => x[0] === this && x[1] === type && x[2] === handler);
      if (entry) return nativeRemove.call(this, type, entry[3], options);
    }
    return nativeRemove.call(this, type, handler, options);
  };
  if (NativeIntersection) window.IntersectionObserver = class extends NativeIntersection {
    constructor(callback, options) {
      const scope = window.__hotelViewScope;
      super((...args) => { if (!scope || scope.active) scoped(scope, callback, undefined, args); }, options);
      scope?.observers.push(this);
    }
  };
  window.MutationObserver = class extends NativeMutation {
    constructor(callback) {
      const scope = window.__hotelViewScope;
      super((...args) => { if (!scope || scope.active) scoped(scope, callback, undefined, args); });
      scope?.observers.push(this);
    }
  };
  let scenePromise;
  let sceneController;
  window.hotel3D = {
    load() {
      if (scenePromise) return scenePromise;
      metrics.sceneLoads++;
      scenePromise = import('./3d/scene.js').then(module => {
        sceneController = scoped(null, module.createWorld, module, []);
        if (!sceneController) throw new Error('WebGL unavailable');
        return sceneController;
      }).catch(error => {
        scenePromise = undefined;
        const stage = document.getElementById('model-stage');
        if (stage) {
          const loading = stage.querySelector('.model-loading');
          loading.textContent = 'The 3D view is unavailable. You can still explore the hotel photographs.';
          const retry = document.createElement('button');
          retry.className = 'button small'; retry.dataset.retryModel = ''; retry.textContent = 'Try 3D again';
          retry.onclick = () => { loading.textContent = 'Preparing your perspective…'; window.hotel3D.load().catch(() => {}); };
          loading.append(retry);
          stage.querySelector('.model-fallback').style.opacity = '1';
        }
        throw error;
      });
      return scenePromise;
    },
    getStats() { return { ...metrics, ...(sceneController?.getStats() || {}), canvases: sceneController ? 1 : 0 }; },
  };

  const assetInfo = window.__HOTEL_ASSETS__ || {};
  function enhanceImage(img) {
    if (img.dataset.optimized === 'true') return;
    const path = new URL(img.getAttribute('src') || '', location.href).pathname;
    const info = assetInfo[path];
    if (!info) return;
    img.dataset.optimized = 'true';
    img.decoding = 'async';
    img.width = info.width; img.height = info.height;
    if (info.srcset && !img.closest('dialog')) {
      img.srcset = info.srcset;
      img.sizes = img.classList.contains('hero-image') || img.closest('.page-hero,.horizon,.final-photo')
        ? '100vw' : '(max-width: 760px) 100vw, 60vw';
    }
    if (img.fetchPriority !== 'high' && !img.closest('.brand') && !img.closest('.page-hero')) img.loading = 'lazy';
  }
  function enhance(root = document) { root.querySelectorAll('img').forEach(enhanceImage); }
  // Unscoped observer supports images generated by all page templates and dialog interactions.
  const images = new NativeMutation(records => {
    for (const record of records) {
      if (record.type === 'attributes') {
        const img = record.target;
        delete img.dataset.optimized; enhanceImage(img);
      } else for (const node of record.addedNodes) if (node.nodeType === 1) {
        if (node.tagName === 'IMG') enhanceImage(node);
        enhance(node);
      }
    }
  });
  images.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['src'] });
  if ('PerformanceObserver' in window) {
    try { new PerformanceObserver(list => { for (const e of list.getEntries()) metrics.largestContentfulPaint = Math.round(e.startTime); }).observe({type:'largest-contentful-paint', buffered:true}); } catch {}
    try { new PerformanceObserver(list => { for (const e of list.getEntries()) if (!e.hadRecentInput) metrics.cumulativeLayoutShift += e.value; }).observe({type:'layout-shift', buffered:true}); } catch {}
  }
  const language = () => new URL(location.href).searchParams.get('lang') || 'en';
  const key = url => url.pathname.replace(/\/$/, '') || '/';
  const collect = () => [...document.body.children].filter(n => n.tagName !== 'SCRIPT');
  const scriptsFor = parsed => [...parsed.querySelectorAll('script[src]')]
    .map(s => s.getAttribute('src')).filter(src => !/runtime|asset-map|\/seo\./.test(src));
  async function execute(src, scope) {
    await new Promise((resolve, reject) => {
      const script = document.createElement('script'); script.src = new URL(src, location.origin).href;
      window.__hotelViewScope = scope;
      script.onload = () => { window.__hotelViewScope = null; script.remove(); resolve(); };
      script.onerror = () => { window.__hotelViewScope = null; script.remove(); reject(new Error('Page script could not load')); };
      document.body.append(script);
    });
  }
  function dispose(view) {
    for (const [target, type, , wrapped, options] of view.listeners) nativeRemove.call(target, type, wrapped, options);
    view.observers.forEach(observer => observer.disconnect());
  }
  let navigating = false;
  async function navigate(url, fromHistory = false) {
    if (navigating) return;
    navigating = true;
    const requested = key(url);
    document.querySelector('main')?.setAttribute('aria-busy', 'true');
    try {
      let next = views.get(requested);
      let parsed;
      if (!next) {
        const response = await fetch(url.pathname + url.search, {headers:{'X-Frontend-Navigation':'1'}});
        if (!response.ok) throw new Error('Route unavailable');
        parsed = new DOMParser().parseFromString(await response.text(), 'text/html');
        if (!parsed.querySelector('main') || !parsed.body.dataset.page) throw new Error('Invalid route');
        next = {active:false, listeners:[], observers:[], page:parsed.body.dataset.page, nodes:[...parsed.body.children].filter(n => n.tagName !== 'SCRIPT'), className:parsed.body.className, title:parsed.title};
      }
      for (const dialog of document.querySelectorAll('dialog[open]')) dialog.close();
      // Restore the persistent stage to its original home before detaching the home view.
      if (current.page === 'home') {
        const stage = document.getElementById('model-stage'), home = document.getElementById('stage-home');
        if (stage && home) home.after(stage);
        document.dispatchEvent(new CustomEvent('immersivechange', {detail:false}));
      }
      current.nodes = collect(); current.title = document.title; current.active = false;
      current.nodes.forEach(n => n.remove());
      document.body.className = next.className; document.body.dataset.page = next.page;
      next.nodes.forEach(n => document.body.append(n)); next.active = true; current = next;
      if (!fromHistory) history.pushState({}, '', url);
      document.title = next.title;
      if (parsed) {
        for (const src of scriptsFor(parsed)) await execute(src, next);
        next.title = document.title;
        views.set(requested, next);
      }
      document.documentElement.dataset.mood = 'day';
      document.dispatchEvent(new CustomEvent('timechange', {detail:'day'}));
      document.dispatchEvent(new CustomEvent('hotelroutechange', {detail:{page:next.page}}));
      window.hotelUpdateSeo?.();
      enhance(); metrics.clientNavigations++;
      window.scrollTo({top:0, behavior:'instant'});
      if (url.hash) document.getElementById(decodeURIComponent(url.hash.slice(1)))?.scrollIntoView({behavior:'instant'});
      for (const [oldKey, view] of views) {
        if (views.size <= 8) break;
        if (view !== current && view.page !== 'home') { dispose(view); views.delete(oldKey); }
      }
    } catch {
      location.assign(url.href); // Native navigation preserves a working site on unsupported transitions.
    } finally {
      document.querySelector('main')?.removeAttribute('aria-busy'); navigating = false;
    }
  }
  window.hotelNavigate = href => navigate(new URL(href, location.href));
  nativeAdd.call(document, 'DOMContentLoaded', () => {
    window.__hotelViewScope = null;
    initial.nodes = collect(); initial.className = document.body.className; initial.title = document.title;
    views.set(key(new URL(location.href)), initial); enhance();
    nativeAdd.call(document, 'click', event => {
      const anchor = event.target.closest('a[href]');
      if (!anchor || event.defaultPrevented || event.button !== 0 || event.ctrlKey || event.metaKey || event.shiftKey || event.altKey || anchor.target || anchor.download) return;
      const url = new URL(anchor.href);
      if (url.origin !== location.origin || (url.searchParams.get('lang') || 'en') !== language()) return;
      if (key(url) === key(new URL(location.href))) return;
      if (!/\/$/.test(url.pathname) && !/\.html$/.test(url.pathname)) return;
      event.preventDefault(); navigate(url);
    });
    nativeAdd.call(window, 'popstate', () => navigate(new URL(location.href), true));
    if ('serviceWorker' in navigator && (location.protocol === 'https:' || ['127.0.0.1','localhost'].includes(location.hostname))) {
      // Warm only the small shell; image/3D caching begins only after actual use.
      const register = () => navigator.serviceWorker.register('/sw.js').catch(() => {});
      if ('requestIdleCallback' in window) requestIdleCallback(register, {timeout:2500}); else setTimeout(register, 1200);
    }
  });
})();
