import * as T from '../vendor/three.module.js';
import {buildReferenceDome} from './dome-model.js?v=7';
let worldInstance;
const stage=document.getElementById('model-stage');
export function createWorld(){
 if(worldInstance)return worldInstance;
 let frames=0,raf=0,contextLost=false,disposed=false;
 const stats=window.hotelPerformance;
 const invalidate=()=>{if(!raf&&!disposed&&!contextLost&&visible&&!document.hidden)raf=requestAnimationFrame(frame)};
 const stop=()=>{cancelAnimationFrame(raf);raf=0};
 let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch(e){stage.querySelector('.model-loading').textContent='Explore the hotel photography — 3D is unavailable on this device.';stage.querySelector('.model-fallback').style.opacity='1';return;}
 stats.renderersCreated++;renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width: 760px)').matches?1.25:1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.90;stage.prepend(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.1,150);let angle=.65,elevation=.54,distance=12,targetAngle=angle,targetElevation=elevation,targetDistance=distance,rotate=false,visible=false,dragging=false,lastX=0,lastY=0,night=false;let guided=true,roofTarget=0,roofLift=0,phase=-1;const target=new T.Vector3(0,.95,0);const section=document.getElementById('architecture');const homeDistance=()=>Math.max(11,11/Math.max(.35,(stage.clientWidth||800)/(stage.clientHeight||600)));distance=targetDistance=homeDistance();
 const model=buildReferenceDome();stats.modelBuilds++;scene.add(model.root);let windowsTarget=0,windowsAmount=0;
 let environmentSource,environmentTarget;
 function refreshEnvironment(){if(!environmentSource||contextLost||disposed)return;const pmrem=new T.PMREMGenerator(renderer);try{environmentTarget?.dispose();environmentTarget=pmrem.fromEquirectangular(environmentSource);scene.environment=environmentTarget.texture;scene.environmentIntensity=.9;}finally{pmrem.dispose();}invalidate();}
 new T.TextureLoader().load('assets/desert.jpg',texture=>{if(disposed){texture.dispose();return;}environmentSource=texture;texture.mapping=T.EquirectangularReflectionMapping;texture.colorSpace=T.SRGBColorSpace;refreshEnvironment();},undefined,()=>invalidate());
 const shadow=new T.Mesh(new T.CircleGeometry(5.2,80),new T.ShadowMaterial({opacity:.15}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.067;shadow.receiveShadow=true;scene.add(shadow);
 const interiorLight=model.light;
 const starPositions=[];let seed=19;function rand(){seed=(seed*16807)%2147483647;return (seed-1)/2147483646}for(let i=0;i<400;i++){const az=rand()*Math.PI*2,el=.07+rand()*1.25,r=20+rand()*6;starPositions.push(Math.sin(az)*Math.cos(el)*r,Math.sin(el)*r,Math.cos(az)*Math.cos(el)*r)}const starsG=new T.BufferGeometry();starsG.setAttribute('position',new T.Float32BufferAttribute(starPositions,3));const starsMat=new T.PointsMaterial({color:0xf7f5f1,size:.045,transparent:true,opacity:0,depthWrite:false});scene.add(new T.Points(starsG,starsMat));
 const ambient=new T.HemisphereLight(0xfff7eb,0x9f866c,1.8);scene.add(ambient);const sunlight=new T.DirectionalLight(0xffe6c8,2.5);sunlight.position.set(-4,8,7);sunlight.castShadow=true;const shadowSize=matchMedia('(max-width: 760px)').matches?512:1024;sunlight.shadow.mapSize.set(shadowSize,shadowSize);sunlight.shadow.camera.left=-7;sunlight.shadow.camera.right=7;sunlight.shadow.camera.top=7;sunlight.shadow.camera.bottom=-7;sunlight.shadow.normalBias=.025;scene.add(sunlight);const fill=new T.DirectionalLight(0xffeed7,.85);fill.position.set(6,5,-4);scene.add(fill);
 const resize=()=>{const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();};const sizeObserver=new ResizeObserver(resize);sizeObserver.observe(stage);resize();stage.classList.add('ready');stage.querySelector('.model-fallback').style.opacity='';
 function setRotate(value){rotate=value;const b=document.getElementById('rotate-model');b.setAttribute('aria-pressed',value);b.textContent=value?'Pause':'Rotate';}
 function stopGuide(){guided=false;setRotate(false);document.getElementById('reset-model').textContent='Follow scroll';}
 function setRoof(value){roofTarget=value?1:0;document.getElementById('cutaway-model').setAttribute('aria-pressed',value);document.getElementById('cutaway-model').textContent=value?'Show shell':'Look inside';}
 function setPhase(i){if(i===phase)return;phase=i;const names=['arrival','terrace','inside'];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===names[i]));document.getElementById('chapter-copy').textContent=['Copper, honey and smoked-bronze mirror glass. Every facet catches the light differently.','Explore the reflective glass facade and open the two hinged windows.','Inspect the room from above. Switch between king and twin layouts, with a bathroom behind the beds.'][i];}
 function chooseView(name){stopGuide();const idx=['arrival','terrace','inside'].indexOf(name);setPhase(idx);targetAngle=[.65,-.38,0][idx];targetElevation=[.42,.24,1.48][idx];targetDistance=homeDistance()*[1,.86,.90][idx];setRoof(idx===2);}
 document.getElementById('rotate-model').onclick=()=>{guided=false;setRotate(!rotate)};
 document.getElementById('cutaway-model').onclick=()=>{stopGuide();setRoof(!roofTarget);if(roofTarget){targetElevation=1.22;targetDistance=homeDistance()*.86;setPhase(2)}};
 document.getElementById('zoom-in').onclick=()=>{stopGuide();targetDistance=Math.max(6,targetDistance-1)};document.getElementById('zoom-out').onclick=()=>{stopGuide();targetDistance=Math.min(homeDistance()*1.5,targetDistance+1)};
 document.getElementById('reset-model').onclick=()=>{guided=!document.getElementById('immersive').open;targetAngle=.65;targetElevation=.54;targetDistance=homeDistance();setRoof(false);setPhase(0);setRotate(false)};
 document.getElementById('plan-model').onclick=()=>chooseView('inside');
 document.getElementById('windows-model').onclick=()=>{stopGuide();windowsTarget=windowsTarget?0:1;document.getElementById('windows-model').setAttribute('aria-pressed',Boolean(windowsTarget));document.getElementById('windows-model').textContent=windowsTarget?'Close windows':'Open windows';if(roofTarget)chooseView('terrace')};
 document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>{model.setLayout(b.dataset.layout);document.querySelectorAll('[data-layout]').forEach(x=>x.setAttribute('aria-pressed',x===b));chooseView('inside')});
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>chooseView(b.dataset.view));document.addEventListener('immersivechange',e=>{guided=!e.detail;targetDistance=homeDistance();setRotate(false)});
 stage.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;dragging=true;lastX=e.clientX;lastY=e.clientY;stage.setPointerCapture(e.pointerId);stage.classList.add('dragging');stopGuide()});stage.addEventListener('pointermove',e=>{if(!dragging)return;targetAngle-=(e.clientX-lastX)*.008;targetElevation=Math.max(.18,Math.min(1.5,targetElevation+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY});const end=()=>{dragging=false;stage.classList.remove('dragging')};stage.addEventListener('pointerup',end);stage.addEventListener('pointercancel',end);stage.addEventListener('keydown',e=>{const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='];if(!keys.includes(e.key))return;e.preventDefault();stopGuide();if(e.key==='ArrowLeft')targetAngle+=.15;if(e.key==='ArrowRight')targetAngle-=.15;if(e.key==='ArrowUp')targetElevation=Math.min(1.5,targetElevation+.08);if(e.key==='ArrowDown')targetElevation=Math.max(.18,targetElevation-.08);if(e.key==='+'||e.key==='=')targetDistance=Math.max(7.2,targetDistance-.8);if(e.key==='-')targetDistance=Math.min(homeDistance()*1.4,targetDistance+.8)});
 const visibility=new IntersectionObserver(es=>{visible=es[0].isIntersecting;if(visible)invalidate();else stop();},{rootMargin:'0px'});visibility.observe(stage);
 document.addEventListener('motionchange',()=>{if(window.motionPaused)setRotate(false);invalidate();});
 document.addEventListener('timechange',e=>{night=e.detail==='night';section.dataset.night=String(night);document.getElementById('immersive')?.setAttribute('data-night',String(night));invalidate();});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else invalidate();});
 document.addEventListener('hotelroutechange',e=>{if(e.detail.page!=='home'){visible=false;stop();}else{resize();invalidate();}});
 window.addEventListener('scroll',invalidate,{passive:true});
 stage.addEventListener('pointermove',invalidate,{passive:true});
 stage.addEventListener('keydown',invalidate);
 document.addEventListener('click',e=>{if(stage.contains(e.target)||e.target.closest('[data-view],[data-time],[data-viewer-time],[data-layout],#open-immersive,.close-immersive'))invalidate();});

 let prev=0;function frame(now){raf=0;if(!stage.isConnected||!visible||document.hidden||contextLost||disposed){prev=now;return}const dt=Math.min((now-prev)/1000,.1);prev=now;
 if(guided&&!window.motionPaused&&!document.getElementById('immersive').open){const rect=section.getBoundingClientRect();const travel=Math.max(1,section.offsetHeight-(innerHeight-82));const progress=T.MathUtils.clamp((82-rect.top)/travel,0,1);document.getElementById('journey-fill').style.transform='scaleX('+progress+')';targetAngle=.65-progress*.65;targetElevation=.35+Math.pow(progress,2)*1.1;targetDistance=homeDistance()*(1-.19*Math.sin(progress*Math.PI));const nextPhase=progress<.32?0:progress<.68?1:2;setPhase(nextPhase);setRoof(progress>.72);}
 if(rotate&&!dragging&&!window.motionPaused)targetAngle+=dt*.12;
 const ease=window.motionPaused?1:1-Math.exp(-dt*8);angle+=(targetAngle-angle)*ease;elevation+=(targetElevation-elevation)*ease;distance+=(targetDistance-distance)*ease;roofLift+=(roofTarget-roofLift)*ease;windowsAmount+=(windowsTarget-windowsAmount)*ease;model.update(roofLift,windowsAmount);
 const lightEase=window.motionPaused?1:1-Math.exp(-dt*7),sunEase=window.motionPaused?1:1-Math.exp(-dt*6);ambient.intensity=T.MathUtils.lerp(ambient.intensity,night?.65:1.8,lightEase);sunlight.intensity=T.MathUtils.lerp(sunlight.intensity,night?.65:2.5,lightEase);fill.intensity=T.MathUtils.lerp(fill.intensity,night?.35:.85,lightEase);interiorLight.intensity=T.MathUtils.lerp(interiorLight.intensity,night?6:2.6,lightEase);starsMat.opacity=T.MathUtils.lerp(starsMat.opacity,night?.9:0,lightEase);sunlight.position.x=T.MathUtils.lerp(sunlight.position.x,night?5:-5,sunEase);
 camera.position.set(Math.sin(angle)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(angle)*Math.cos(elevation)*distance);camera.lookAt(target);renderer.render(scene,camera);frames++;
 const unsettled=Math.abs(targetAngle-angle)+Math.abs(targetElevation-elevation)+Math.abs(targetDistance-distance)+Math.abs(roofTarget-roofLift)+Math.abs(windowsTarget-windowsAmount)+Math.abs((night?.65:1.8)-ambient.intensity)+Math.abs((night?.65:2.5)-sunlight.intensity)+Math.abs((night?.35:.85)-fill.intensity)+Math.abs((night?6:2.6)-interiorLight.intensity)+Math.abs((night?.9:0)-starsMat.opacity)+Math.abs((night?5:-5)-sunlight.position.x)>.003;
 if((rotate&&!window.motionPaused)||dragging||unsettled)invalidate();
 }
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;stop();stage.classList.remove('ready');stage.querySelector('.model-loading').textContent='3D is paused while your device restores graphics. Hotel photographs remain available.';});
 renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;refreshEnvironment();renderer.shadowMap.needsUpdate=true;stage.classList.add('ready');resize();invalidate();});
 function dispose(){if(disposed)return;disposed=true;stop();visibility.disconnect();sizeObserver.disconnect();const geometries=new Set(),materials=new Set(),textures=new Set();scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of [o.material].flat().filter(Boolean)){materials.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v);}});geometries.forEach(g=>g.dispose());textures.forEach(t=>t.dispose());materials.forEach(m=>m.dispose());environmentTarget?.dispose();environmentSource?.dispose();renderer.dispose();}
 addEventListener('pagehide',e=>{if(!e.persisted)dispose();});
 worldInstance={invalidate,dispose,getStats:()=>({frames,visible,contextLost,idle:!raf,batching:model.stats.batching,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures})};
 invalidate();return worldInstance;
}
