const A='assets/';const reduced=matchMedia('(prefers-reduced-motion: reduce)');window.motionPaused=reduced.matches;let room=0,photo=0;const rooms=[{name:'Deluxe Double',img:'room-2-0.jpg',size:'36 m²',beds:'Twin beds',copy:'Soft light, warm textures, and space to exhale. A restful base for travelling companions after a day of desert discovery.'},{name:'Superior Single',img:'room-6-0.jpg',size:'25 m²',beds:'King-size bed',copy:'A personal sanctuary framed by the mountains. Settle in, switch off, and enjoy a little space that is entirely your own.'},{name:'Standard Triple',img:'room-5-0.jpg',size:'28 m²',beds:'Three single beds',copy:'For shared adventures and stories that last. Three individual beds give every guest a comfortable place to return to.'}];
const photos=[{img:'hero.jpg',title:'A place of your own',alt:'Dome rooms beneath the desert mountains'},{img:'desert.jpg',title:'Slow afternoons, wide horizons',alt:'The pool and hotel in the desert'},{img:'04-1.jpg',title:'Under a sky full of possibility',alt:'Milky Way above a hotel dome'},{img:'03-1.jpg',title:'A different kind of neighbourhood',alt:'Dome accommodation in the desert'},{img:'05-1.jpg',title:'When the world turns quiet',alt:'Sahara Sky lit up at night'}];
function motion(){document.body.classList.toggle('motion-paused',window.motionPaused);document.querySelectorAll('.motion-button').forEach(b=>{b.textContent=window.motionPaused?'Enable motion':'Pause motion';b.setAttribute('aria-pressed',window.motionPaused)});document.dispatchEvent(new Event('motionchange'))}motion();document.querySelectorAll('.motion-button').forEach(b=>b.onclick=()=>{window.motionPaused=!window.motionPaused;motion()});reduced.addEventListener('change',e=>{window.motionPaused=e.matches;motion()});
const nav=document.querySelector('.nav'),hero=document.querySelector('.hero'),horizon=document.querySelector('.horizon');let pending=false;function onScroll(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;const y=scrollY,doc=document.documentElement;doc.style.setProperty('--scroll',y/Math.max(1,doc.scrollHeight-innerHeight));nav.classList.toggle('scrolled',y>55);if(!window.motionPaused){hero.style.setProperty('--hero-y',Math.min(y*.2,250)+'px');const r=horizon.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)horizon.style.setProperty('--landscape-y',(r.top-innerHeight/2)*.1+'px')}})}addEventListener('scroll',onScroll,{passive:true});onScroll();const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
function setTime(time){hero.dataset.time=time;document.querySelectorAll('[data-time]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',b.dataset.time===time)});document.dispatchEvent(new CustomEvent('timechange',{detail:time}));}
function openBooking(experience){if(experience)document.querySelector('[name=experience]').value=experience;document.getElementById('form-result').textContent='';document.getElementById('booking').showModal()}
function detail(html){document.getElementById('detail-body').innerHTML=html;const d=document.getElementById('detail');if(!d.open)d.showModal()}
function selectRoom(i){room=i;const r=rooms[i];const image=document.getElementById('room-image');image.src=A+r.img;image.alt=r.name+' room interior';document.getElementById('room-counter').textContent='0'+(i+1)+' / 03';document.getElementById('room-name').textContent=r.name;document.getElementById('room-specs').innerHTML=`<span>${r.size}</span><span>${r.beds}</span>`;document.getElementById('room-copy').textContent=r.copy;document.querySelectorAll('[data-room]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.room===i))}
const reel=document.getElementById('photo-reel');reel.innerHTML=photos.map((p,i)=>`<button class="photo-card" data-photo="${i}" aria-label="Open photograph: ${p.title}"><img draggable="false" src="${A+p.img}" alt="${p.alt}" loading="lazy"><span>0${i+1} / ${p.title}</span></button>`).join('');function positionPhotos(){const mobile=innerWidth<760;reel.querySelectorAll('.photo-card').forEach((b,i)=>{let offset=i-photo;if(offset>2)offset-=photos.length;if(offset< -2)offset+=photos.length;const x=offset*(mobile?215:330),z=-Math.abs(offset)*(mobile?120:160),rot=offset*-16;b.style.transform=`translateX(calc(-50% + ${x}px)) translateZ(${z}px) rotateY(${rot}deg) rotateZ(${offset*2}deg)`;b.style.opacity=Math.abs(offset)>1?'.45':'1';b.style.zIndex=10-Math.abs(offset);b.tabIndex=Math.abs(offset)>1?-1:0});document.getElementById('gallery-count').textContent='0'+(photo+1)+' / 05'}function movePhotos(n){photo=(photo+n+photos.length)%photos.length;positionPhotos()}positionPhotos();addEventListener('resize',positionPhotos);let startX=0,dragged=false;reel.addEventListener('pointerdown',e=>{startX=e.clientX;dragged=false});reel.addEventListener('pointerup',e=>{if(Math.abs(e.clientX-startX)>35){dragged=true;movePhotos(e.clientX<startX?1:-1);setTimeout(()=>dragged=false,100)}});document.getElementById('gallery-prev').onclick=()=>movePhotos(-1);document.getElementById('gallery-next').onclick=()=>movePhotos(1);
if(matchMedia('(pointer:fine)').matches)document.querySelectorAll('.tilt-card').forEach(el=>{el.addEventListener('pointermove',e=>{if(window.motionPaused)return;const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`rotateY(${x*7}deg) rotateX(${-y*6}deg)`});el.addEventListener('pointerleave',()=>el.style.transform='')});
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.hasAttribute('data-book'))openBooking();if(b.classList.contains('close'))b.closest('dialog').close();if(b.classList.contains('menu-toggle')){const open=document.getElementById('nav-links').classList.toggle('open');b.setAttribute('aria-expanded',open)}if(b.closest('#nav-links')){document.getElementById('nav-links').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded',false)}if(b.dataset.time)setTime(b.dataset.time);if(b.dataset.room!==undefined)selectRoom(+b.dataset.room);if(b.id==='room-expand'){const r=rooms[room];detail(`<span class="eyebrow">YOUR ROOM AT SAHARA SKY</span><h2>${r.name}</h2><img src="${A+r.img}" alt="${r.name} room interior"><p>${r.size} · ${r.beds}<br>${r.copy}</p><button class="button" data-detail-book>Choose your dates</button>`)}if(b.hasAttribute('data-detail-book')){document.getElementById('detail').close();openBooking()}if(b.dataset.photo!==undefined&&!dragged){const p=photos[+b.dataset.photo];if(+b.dataset.photo!==photo){photo=+b.dataset.photo;positionPhotos()}else detail(`<span class="eyebrow">POSTCARDS FROM OUR WORLD</span><h2>${p.title}</h2><img src="${A+p.img}" alt="${p.alt}">`)}if(b.dataset.experience){const safari=b.dataset.experience==='desert';detail(`<span class="eyebrow">${safari?'DAYS OF DISCOVERY':'NIGHTS OF WONDER'}</span><h2>${safari?'Follow the horizon.':'Look up. Stay a while.'}</h2><img src="${A+(safari?'exterior.jpg':'04-1.jpg')}" alt="${safari?'The hotel and Western Desert landscape':'Stars above a desert dome'}"><p>${safari?'Make Sahara Sky your base for exploring the Black and White Deserts. Add a safari to your stay enquiry; routes, duration and inclusions are to be confirmed with the hotel.':'Return from a day of discovery to the open desert sky. Take your time beneath the stars. Visibility depends on weather, moonlight and the season.'}</p><button class="button" data-plan="${safari?'A room & desert safari':'A room & stargazing'}">Include in my stay</button>`)}if(b.dataset.plan){document.getElementById('detail').close();openBooking(b.dataset.plan)}});
const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const today=new Date(),next=new Date(today);next.setDate(next.getDate()+1);const arrival=document.querySelector('[name=arrival]'),departure=document.querySelector('[name=departure]');arrival.min=localDate(today);departure.min=localDate(next);arrival.onchange=()=>{const d=new Date(arrival.value+'T12:00:00');if(!Number.isNaN(d.getTime())){d.setDate(d.getDate()+1);departure.min=localDate(d)}};document.getElementById('stay-form').onsubmit=e=>{e.preventDefault();const v=new FormData(e.target),r=document.getElementById('form-result');if(v.get('departure')<=v.get('arrival')){r.textContent='Please choose a check-out date after check-in.';return}const n=Math.round((new Date(v.get('departure'))-new Date(v.get('arrival')))/86400000);r.textContent=`Your stay preview: ${n} night${n===1?'':'s'}, ${v.get('adults')} adult(s), ${v.get('children')} child(ren). ${v.get('experience')}. ${v.get('arrival')} – ${v.get('departure')}. No reservation has been made.`};document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
const stage=document.getElementById('model-stage');
const startWorld=()=>window.hotel3D.load().then(()=>document.dispatchEvent(new CustomEvent('timechange',{detail:hero.dataset.time}))).catch(()=>{});
const loadWorld=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){loadWorld.disconnect();startWorld();}},{rootMargin:navigator.connection?.saveData?'0px':'180px'});loadWorld.observe(stage);
// The immersive view reuses the same scene, keeping its state and GPU resources.
const immersive=document.getElementById('immersive'),stageHome=document.getElementById('stage-home');
document.getElementById('open-immersive').onclick=()=>{startWorld();document.getElementById('immersive-stage').append(stage);immersive.showModal();document.dispatchEvent(new CustomEvent('immersivechange',{detail:true}));};
document.querySelector('.close-immersive').onclick=()=>immersive.close();
immersive.addEventListener('close',()=>{stageHome.after(stage);document.dispatchEvent(new CustomEvent('immersivechange',{detail:false}));document.getElementById('open-immersive').focus({preventScroll:true})});
document.querySelectorAll('[data-viewer-time]').forEach(b=>b.onclick=()=>{setTime(b.dataset.viewerTime);document.querySelectorAll('[data-viewer-time]').forEach(x=>x.setAttribute('aria-pressed',x===b))});
document.addEventListener('timechange',e=>document.querySelectorAll('[data-viewer-time]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.viewerTime===e.detail)));
